on: 
  push:
    branches:
      - main 
      - test 

jobs:
  check-for-updates:
    runs-on: ubuntu-latest
    outputs:
      update: ${{steps.check-for-updates.update_step.updatesAvailable}}
      test: "123"

    steps:
    - uses: actions/checkout@v1

    - id: update_step
      shell: pwsh
      name: Check for updates
      run: | 
        $updatesAvailable = .\updater.ps1
        Write-Host "are there any updates available? [$updatesAvailable]"
        echo "::set-output name=update::$updatesAvailable"

    - run: echo "updatesAvailable = [${{ steps.update_step.outputs.update }}]"

  run-update:
    runs-on: ubuntu-latest
    needs: check-for-updates
    #if: ${{ needs.check-for-updates.steps.update_step.outputs.updates }}" == "False"
    steps:
    - run: echo "updatesAvailable1 = [${{ needs.check-for-updates.outputs.update }}]"
    - run: echo "updatesAvailable2 = [${{ steps.update_step.outputs.update }}]"
    - run: echo "test1 = [${{ needs.check-for-updates.outputs.test }}]"
    - run: echo "test2 = [${{ steps.update_step.outputs.test }}]"
