on: 
  push:
    branches:
      - main 
      - test 

jobs:
  check-for-updates:
    runs-on: ubuntu-latest
    outputs:
      update: ${{steps.check-for-updates.update_step.updatesAvailable}}

    steps:
    - uses: actions/checkout@v1

    - id: update_step
      shell: pwsh
      name: Check for updates
      run: | 
        $updatesAvailable = .\updater.ps1
        Write-Host "are there any updates available? [$updatesAvailable]"
        echo "::set-output name=updates::$updatesAvailable"

    - run: echo "updatesAvailable = ${{ steps.update_step.outputs.updates }}"

  run-update:
    runs-on: ubuntu-latest
    needs: check-for-updates
    if: ${{ needs.check-for-updates.steps.update_step.outputs.updates }}" == "True"
    steps:
    - run: echo 'hello world'
    - run: echo "updatesAvailable = ${{ needs.check-for-updates.steps.update_step.outputs.updates }}"
