on: 
  push:
    branches:
      - main 
      - test 

jobs:
  check-for-updates:
    runs-on: ubuntu-latest
    outputs:
      update: ${{steps.check-for-updates.update_step.updatesAvailable}}

    steps:
    - uses: actions/checkout@v1

    - id: update_step
      shell: pwsh
      name: Check for updates
      run: | 
        $updatesAvailable = .\updater.ps1
        Write-Host "are there any updates available? $updatesAvailable"
        echo "::set-output name=updatesAvailable::$updatesAvailable"

  run-update:
    runs-on: ubuntu-latest
    needs: check-for-updates
    steps:
    - run: echo 'hello world'
    - run: echo "${{ jobs.check-for-updates.steps.update_step.outputs.updatesAvailable }}"
